# Generated by Django 5.0.1 on 2024-02-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userdata_delete_signin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
